#cloud-config
# yaml-language-server: $schema=https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/versions.schema.cloud-config.json
runcmd:
  - hostnamectl hostname azuma
  # - [
  #     "tailscale",
  #     "up",
  #     "--accept-risk=all",
  #     "--json",
  #     "--ssh",
  #     "--auth-key={{ TS_AUTH_KEY }}",
  #   ]
write_files:
  - path: /etc/userdb/vesu.user-privileged
    content: |
      {
        "privileged": {
          "sshAuthorizedKeys": [
            ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKoabiCtKYWtp5hr2CpFN2RnIZKrpx1rt5f42Dq8Ykay greatpigeon@gp-Z370
          ]
        }
      }
    owner: root:root
    permissions: "0o600"
    encoding: text/plain
    append: false
    defer: false
power_state:
  mode: reboot
  message: Rebooting after initial setup
  timeout: 300
  condition: true
