#cloud-config
# yaml-language-server: $schema=https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/versions.schema.cloud-config.json
runcmd:
  - hostnamectl hostname azuma
  - mkhomedir_helper vesu
  - loginctl enable-linger vesu
  - [
      "tailscale",
      "up",
      "--accept-risk=all",
      "--json",
      "--ssh",
      "--auth-key=tskey-auth-kJM5rDvQW111CNTRL-dRCgHZwFyUdPz5EPsTBuadoKaEq2cimG",
    ]
