#cloud-config
# yaml-language-server: $schema=https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/versions.schema.cloud-config.json
runcmd:
  - hostnamectl hostname {{ hostname }}
  - mkhomedir_helper {{ user }}
  - loginctl enable-linger {{ user }}
  - [
      "tailscale",
      "up",
      "--accept-risk=all",
      "--json",
      "--ssh",
      "--auth-key={{ TS_AUTH_KEY }}",
    ]
