FROM quay.io/fedora/fedora-bootc:42

RUN echo '[etc]' >> /usr/lib/ostree/prepare-root.conf \
    && echo 'transient = true' >> /usr/lib/ostree/prepare-root.conf

COPY ./system/wheel-passwordless-sudo /etc/sudoers.d/wheel-passwordless-sudo
COPY --chmod=0644 ./sysusers.conf /usr/lib/sysusers.d/podman.conf

# Packages
COPY --chmod=0644 ./packages.json /usr/local/share/bootc/packages.json
RUN jq -r .packages[] /usr/share/rpm-ostree/treefile.json > /usr/local/share/bootc/packages-centos-bootc \
    && jq -r '.add | flatten | join(" ")' /usr/local/share/bootc/packages.json
RUN --mount=type=cache,id=libdnf,target="/var/lib/dnf" \
    --mount=type=cache,id=cachednf,target="/var/cache/dnf" \
  dnf -y install dnf5-plugins \
  && dnf -y copr enable wezfurlong/wezterm-nightly \
  && dnf -y config-manager addrepo --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo

RUN --mount=type=cache,id=libdnf,target="/var/lib/dnf" \
    --mount=type=cache,id=cachednf,target="/var/cache/dnf" \
  dnf -y --no-docs --refresh install --allowerasing $(jq -r '.add | flatten | join(" ")' "/usr/local/share/bootc/packages.json") \
  && dnf -y remove $(jq -r '.remove | flatten | join(" ")' "/usr/local/share/bootc/packages.json") \
  && rm /usr/bin/wezterm-gui \
  && dnf -y autoremove \
  && dnf clean all

COPY ./wezterm.terminfo /tmp/wezterm.terminfo
RUN tic -x -o /usr/share/terminfo /tmp/wezterm.terminfo

# config
COPY --chmod=0755 ./scripts/* /usr/local/bin/
COPY --chmod=0644 ./system/etc_skel_bashrcd /etc/skel/.bashrc.d/bootc
COPY --chmod=0644 ./system/kargs_00-console.toml /usr/lib/bootc/kargs.d/00-console.toml
COPY --chmod=0644 ./system/sshd_config_99-systemd-homed.conf /etc/ssh/sshd_config.d/99-systemd-homed.conf

# RUN /usr/local/bin/user-conf

# Users
# COPY --chmod=0644 ./vesu.json /usr/lib/userdb/vesu.user
# COPY --chmod=0644 ./vesu.json /usr/lib/credstore/home.create.vesu

# RUN useradd vesu \
#   -u 1000 \
#   -K SUB_GID_MIN=1000001 \
#   -K SUB_UID_MIN=1000001 \
#   -G wheel,podman \
#   -s /usr/bin/fish \
#   -p '$y$j9T$rgIIgXU.iiGCNeGeo27Va1$.UbQgNafnJ0.OX7MIYunDIKU2T5dySSoLuC8I9kxke6'

# RUN mkdir -p /var/containers/systemd/users \
#   && ln -s /var/containers /etc \
#   && chmod 0755 /var/containers/systemd

COPY --chmod=0644 ./vesu.user.json /usr/lib/userdb/vesu.user
COPY --chmod=0600 ./vesu.user-privileged.json /usr/lib/userdb/vesu.user-privileged
RUN ln -s /usr/lib/userdb/vesu.user /usr/lib/userdb/1003.user \
    && ln -s /usr/lib/userdb/vesu.user-privileged /usr/lib/userdb/1003.user-privileged

# SYSTEMD
COPY --chmod=0644 ./systemd/firstboot-setup.service /usr/lib/systemd/system/firstboot-setup.service

# RUN authselect enable-feature with-systemd-homed

# RUN systemctl enable systemd-homed.service cockpit.socket firstboot-setup.service systemd-homed-firstboot.service
RUN systemctl enable cockpit.socket firstboot-setup.service
RUN systemctl enable podman.service podman-auto-update.service podman-clean-transient.service podman.socket

RUN rm /var/{log,cache,lib}/* -rf

# CLEAN & CHECK
RUN bootc container lint

# vim: set ft=dockerfile:
