FROM quay.io/fedora/fedora-bootc:42

COPY ./system/wheel-passwordless-sudo /etc/sudoers.d/wheel-passwordless-sudo
COPY --chmod=0644 ./sysusers.conf /usr/lib/sysusers.d/podman.conf

# Packages
COPY --chmod=0770 ./pkgs/repos.sh /usr/local/share/bootc/repos.sh

RUN --mount=type=cache,id=libdnf,target="/var/lib/dnf" \
    --mount=type=cache,id=cachednf,target="/var/cache/dnf" \
    /usr/bin/bash /usr/local/share/bootc/repos.sh

COPY --chmod=0644 ./pkgs/packages.json /usr/local/share/bootc/packages.json
COPY --chmod=0770 ./pkgs/installs.sh /usr/local/share/bootc/installs.sh
ARG eza_version="v0.21.6"
ENV EZA_VERSION=${eza_version}
RUN --mount=type=cache,id=libdnf,target="/var/lib/dnf" \
    --mount=type=cache,id=cachednf,target="/var/cache/dnf" \
    /usr/bin/bash /usr/local/share/bootc/installs.sh


# Add wezterm terminfo
COPY ./wezterm.terminfo /tmp/wezterm.terminfo
RUN tic -x -o /usr/share/terminfo /tmp/wezterm.terminfo

# config
COPY --chmod=0644 ./system/skel/ /etc/skel/
COPY --chmod=0644 ./system/etc-firewalld/ /etc/firewalld/
COPY --chmod=0644 ./system/kargs_00-console.toml /usr/lib/bootc/kargs.d/00-console.toml
COPY --chmod=0644 ./system/sshd_config_99-systemd-userdbd.conf /etc/ssh/sshd_config.d/99-systemd-userdbd.conf

# Set up user namespace sub{u,g}id
COPY --chmod=0755 ./scripts/user-conf /tmp/user-conf
RUN /tmp/user-conf

COPY ./userdb/ /usr/lib/userdb/
RUN chmod 0644 /usr/lib/userdb/vesu.user /usr/lib/userdb/vesu.group \
    && chmod 0600 /usr/lib/userdb/vesu.user-privileged \
    && ln -s /usr/lib/userdb/vesu.user /usr/lib/userdb/1003.user \
    && ln -s /usr/lib/userdb/vesu.group /usr/lib/userdb/1003.group \
    && ln -s /usr/lib/userdb/vesu.user-privileged /usr/lib/userdb/1003.user-privileged

# systemd
RUN systemctl enable cockpit.socket tailscaled.service \
  podman.service podman-auto-update.service podman-clean-transient.service podman.socket 

RUN rm /var/{log,cache,lib}/* -rf

# CLEAN & CHECK
RUN bootc container lint

# vim: set ft=dockerfile:
