#!/usr/bin/bash

###############################################
# Setup HOST
###############################################

HOST_NAME=${HOST_NAME:-"bootc"}
hostnamectl hostname "$HOST_NAME"

###############################################
# Setup USERS
###############################################

USERNAME=${USERNAME:-"vesu2"}

homectl firstboot

# usermod -a -G podman "${USERNAME}"
# loginctl enable-linger "${USERNAME}"

###############################################
# Setup FIREWALL
###############################################

# if [ "$(firewall-cmd --get-default-zone)" != "public" ]; then
#   firewall-cmd --set-default-zone=public
# fi
# firewall-cmd --reload

# vim: set ft=bash:
